name: Bug Report
description: Use this form to raise an bug report with the repo
labels: ["bug, new"]
title: "[Bug] - "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A brief description of the bug.
      placeholder: "Bug title"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A detailed description of the bug.
      placeholder: "Bug description"
    validations:
      required: true

  - type: input
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions on how to reproduce the bug.
      placeholder: "1. Step one\n2. Step two\n3. Step three"
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: "Expected behavior"
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: "Actual behavior"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Relevant information about the environment in which the bug occurs (e.g., browser, operating system).
      placeholder: "Environment details"
    validations:
      required: true
