name: Enhancement request
description: Suggest an enhancement for the project
title: "[ENHANCEMENT] "
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement!

  - type: input
    id: title
    attributes:
      label: Enhancement Title
      description: A brief title for the enhancement.
      placeholder: "Enhancement title"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Enhancement Description
      description: A detailed description of the enhancement.
      placeholder: "Enhancement description"
    validations:
      required: true

  - type: input
    id: benefits
    attributes:
      label: Benefits
      description: The benefits of this enhancement.
      placeholder: "Benefits of the enhancement"
    validations:
      required: true

  - type: input
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions or features you've considered.
      placeholder: "Alternative solutions"
    validations:
      required: false

  - type: input
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the enhancement.
      placeholder: "Additional context"
    validations:
      required: false
