name: Deployment

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev
      - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  tofu-checks:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/tofu_checks.yml
    with:
      tf_var_file: "${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}.tfvars"

  infracost:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=. \
                              --format=json \
                              --out-file=/tmp/infracost-base.json \
                              --terraform-var-file "${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}.tfvars"
        working-directory: ${{ github.workspace }}/tofu

      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        uses: actions/checkout@v4

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          infracost diff --path=. \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json \
                          --terraform-var-file "${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}.tfvars"
        working-directory: ${{ github.workspace }}/tofu

      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                      --repo=$GITHUB_REPOSITORY \
                                      --github-token=${{ github.token }} \
                                      --pull-request=${{ github.event.pull_request.number }} \
                                      --behavior=update \
                                      --policy-path ./policies/cost.rego

  sast-checks:
    uses: ./.github/workflows/sast.yml

  linters:
    uses: ./.github/workflows/linters.yml

  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate TF Docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: '${{ github.workspace }}/tofu'
  
  tofu-plan:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: ./.github/workflows/tofu_plan.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      tf_var_file: "${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}.tfvars"

  tofu-apply:
    if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push'
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.ref }}
            
      - name: Tofu Apply
        uses: ./.github/workflows/tofu_apply.yml
        with:
          environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          tf_var_file: "${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}.tfvars"
