name: Infrastructure Deployment

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev
      - main

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash
    
jobs:
  tofu-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Run Checks
        uses: ./.github/workflows/tofu_checks.yml

  sast-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Run SAST Checks
        uses: ./.github/workflows/sast_checks.yml

  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint Checks
        uses: ./.github/workflows/linters.yml
  
  tofu-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Tofu Plan
        uses: ./.github/workflows/tofu_plan.yml
        with:
          runner: ubuntu-latest
          environment: dev
          gh_environment: dev-plan

  tofu-apply:
    needs:
      - tofu-plan
      - tofu-checks
      - sast-checks
      - lint-checks
    runs-on: ubuntu-latest
    steps:
      - name: Tofu Apply
        uses: ./.github/workflows/tofu_apply.yml
        with:
          runner: ubuntu-latest
          environment: dev
          gh_environment: dev-apply
