name: Port Check

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch: {}

permissions:
  issues: write

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - name: Check port availability
      run: |
        IP_ADDRESS="18.133.134.19"
        PORT="3000"
        echo IP_ADDRESS="18.133.134.19" >> $GITHUB_ENV
        echo PORT="3000" >> $GITHUB_ENV

        if curl --silent --fail --max-time 20 --connect-timeout 10 "http://$IP_ADDRESS:$PORT"; then
          echo "Grafana is available in dev!"
        else
          echo "Grafana is NOT AVAILABLE in DEV!"
          echo "port_unavailable_dev=true" >> $GITHUB_ENV
        fi

    - name: Create Issue if Grafana is not available
      if: env.port_unavailable_dev == 'true'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const issueTitle = 'Grafana Unavailable Alert in DEV';
          const issueBody = `The port ${{ env.PORT }} at IP address ${{ env.IP_ADDRESS_DEV }} is not available. Please check the service.`;
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'port-check'
          });
          const issueExists = issues.data.some(issue => issue.title === issueTitle);
          if (!issueExists) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['port-check']
            });
          }

  prod:
    runs-on: ubuntu-latest
    steps:
    - name: Check port availability
      run: |
        IP_ADDRESS="13.41.241.137"
        PORT="3000"
        echo IP_ADDRESS_PROD="13.41.241.137" >> $GITHUB_ENV
        echo PORT="3000" >> $GITHUB_ENV

        if curl --silent --fail --max-time 20 --connect-timeout 10 "http://$IP_ADDRESS:$PORT"; then
          echo "Grafana is available in prod!"
        else
          echo "Grafana is NOT AVAILABLE in PROD!"
          echo "port_unavailable_prod=true" >> $GITHUB_ENV
        fi
        

    - name: Create Issue if Grafana is not available
      if: env.port_unavailable_prod == 'true'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const issueTitle = 'Grafana Unavailable Alert in PROD';
          const issueBody = `The port ${{ env.PORT }} at IP address ${{ env.IP_ADDRESS }} is not available. Please check the service.`;
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'port-check'
          });
          const issueExists = issues.data.some(issue => issue.title === issueTitle);
          if (!issueExists) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['port-check']
            });
          }
