name: sast

on:
  workflow_call:
    inputs:
      directory:
          type: string
          required: false
          description: 'The directory to run the tools in i.e. where your Terraform code is located'
          default: '/tofu'


defaults:
  run:
    shell: bash
    working-directory: ${{ inputs.directory }}

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.ref }}

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.ref }}

      - name: Run Trivy 
        uses: aquasecurity/trivy-action@0.27.0
        with:
          scan-type: 'config'
          exit-code: '1'
