name: Tofu Apply

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tf_var_file:
        required: true
        type: string
        
defaults:
  run:
    shell: bash

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
    
jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Print Tofu Version
        run: tofu --version

      - name: Get OIDC Token File
        run: |
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r .value > /tmp/web-identity-token

      - name: Tofu Init
        run: tofu init --backend-config="key=${{ github.event.repository.name }}/${{ inputs.environment }}/terraform.tfstate" --var-file="${{ inputs.tf_var_file }}"
        working-directory: ${{ github.workspace }}/tofu

      - name: Tofu Apply
        run: tofu apply --var-file="${{ inputs.tf_var_file }}" -no-color --auto-approve
        working-directory: ${{ github.workspace }}/tofu
