name: Tofu Apply

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'tofu/**'
        
defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'main' && 'prod' || 'dev' }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure OpenTofu
        uses: opentofu/setup-opentofu@12f4debbf681675350b6cd1f0ff8ecfbda62027b # v1.0.4

      - name: Print Tofu Version
        run: tofu --version

      - name: Get OIDC Token File
        run: |
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r .value > /tmp/web-identity-token

      - name: Tofu Init
        run: tofu init --backend-config="key=${{ github.event.repository.name }}/${{ github.base_ref == 'main' && 'prod' || 'dev' }}/terraform.tfstate" --var-file="${{ github.base_ref == 'main' && 'prod' || 'dev' }}.tfvars"
        working-directory: ${{ github.workspace }}/tofu

      - name: Tofu Apply
        run: tofu apply --var-file="${{ github.base_ref == 'main' && 'prod' || 'dev' }}.tfvars" -no-color --auto-approve
        working-directory: ${{ github.workspace }}/tofu
